FROM arm64v8/ubuntu
RUN mkdir /build
VOLUME /build

ENV NODE_VERSION 18.4.0

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

USER root
RUN apt update \
    && apt install -y curl vim 7zip
RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
RUN source ~/.nvm/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH ~/.nvm/v$NODE_VERSION/lib/node_modules
ENV PATH ~/.nvm/versions/node/v$NODE_VERSION/bin:$PATH

WORKDIR /build

#docker run --rm -ti --name test-plugin  -v ~/TouchPortal_Discord_Plugin:/build plugin-ar