FROM arm64v8/ubuntu
RUN mkdir /build

VOLUME /build
RUN apt update
RUN apt install -y curl vim 7zip
RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
RUN . ~/.nvm/nvm.sh && nvm install node




